ch-applications/satisfiability-grover.ipynb
Fixed Issue #27 
IBMQ.get_backend()
is being deprecated.
So, edited IBMQ.get_backend() to ---
IBMQ.get_provider().get_backend()
Updating --->     qiskit-textbook/ch-applications/satisfiability-grover.ipynb
for link of https://community.qiskit.org/textbook/ch4/4.5.html
=> fixed issue 27 by updating satisfiability-grover.ipynb

ch-states/atoms-computation.ipynb
Removing unneeded `the` word in code comments to make the sentence clearer and coherent.
=> Fixing minor typo in code comments

ch-prerequisites/linear_algebra.ipynb
which is specific case
changed to
which is a specific case
Contextually a basis vector is a linearly independent vector spanning Rn.
=> Erratum linear_algebra.ipynb Line 209

content/ch-prerequisites/qiskit.ipynb
Changed
> we also refer to the bits in the classical index by register
to
> we also refer to the bits in the classical register by index
=> fix(prerequisites-qiskit): fix typo

content/ch-gates/quantum-gates.ipynb
The code `gate_latex[0:-4]` is presumably intended to remove the escaped double slashes `\\\\` at the end of the last row of the matrix, but only 2 characters need to be removed because the escape sequences are interpreted before the removal happens. The existing code also erroneously removes the final `0j` which should be displayed.
(It's very confusing because if you look at the raw notebook source code, each slash is escaped again resulting in a sequence of eight slashes `\\\\\\\\`!)
=> Fix LaTeX display of composite gate matrix.

content/ch-states/atoms-computation.ipynb
there was a typo of " he " which should be " the ".
@delapuente @aasfaw
=> fixed a typo in documentation

content/ch-gates/basic-circuit-identities.ipynb
Fixes #134 
From: 
`It performs an X on the target only if both controls are in the state |0>.`
To:
`It performs an X on the target only if both controls are in the state |1>.`
=> Toffoli Controls need to be in state |1>

content/ch-prerequisites/linear_algebra.ipynb
The sentence "A more intutive and geometric definition as that a vector..." has two typos.
1. "intutive" is misspelled and should be "intuitive"'
2. "as that a vector" should be "is that a vector"
=> Fixed two typos in linear_algebra.ipynb

_data/toc.yml
Fixes #128 / https://github.com/Qiskit/qiskit.org/issues/367
Setting the Links of the Section Headings to "external", so jupyter-book doesn't index these and use it as prev/next targets. Because jupyter-book now doesn't care about the links anymore, a ".html"-suffix is necessary.
=> Fix "Next" Links by Setting Section Headings External

content/ch-states/atoms-computation.ipynb, content/ch-states/states-many-qubits.ipynb
Fixed what appear to be two small typos in the textbook. First, in ch-states/atoms-computation, changed a phrase that said qubits were numbered left-to-right, to say instead that qubits are numbered right-to-left.
Secondly, in ch-states/states-many-qubits, there was a term $P^{zz}_{01}$ where the subscript "01" seems incorrect and it should read "1" instead.
=> fixed typos

README.md
Fixes #126.
The Contributors .bib link is currently broken in the Readme.
This PR resolves this issue by updating the link to go to the proper page. To confirm this PR fixed the issue, I visited my [own forked repo](https://github.com/mrthankyou/qiskit-textbook/tree/126_fix_contributors_link), clicked on the .bib link, and was redirected to the correct page.
=> Update contributors .bib link in the Readme

.github/issue_template.md
Fixes #120.
This PR introduces an issue template. This template will be the default template shown to anyone creating a new issue. I have intentionally kept the issue template short and concise to ensure there is as little friction as possible for any first-time contributors.
I welcome any feedback on the issue template itself.
=> Add issue template to Github Project

content/ch-applications/vqe-molecules.ipynb
Fixes #172 
Fixes #116 
Probably Fixes #115 
- Remove ibmqx4 backend in favor of ibmqx2
- Removed deprecated option `operator_mode` from VQE calls ('matrix' and 'grouped_paulis')
- Replaced `qubitOp.two_qubit_reduced_operator` with `Z2Symmetries.two_qubit_reduction`
- Updated Imports to use correct paths of current Qiskit Version
- Replace deprecated `line_length` in favor of `fold` in `draw()`
- Re-Run whole notebook to update values and run counters
The results are pretty near to the ones before.
Though, someone familiar with the topic should take a look please :)
=> Refactoring VQE Molecules Notebook to work with current Qiskit Version

content/ch-quantum-hardware/measurement-error-mitigation.ipynb
The textbook claimed that "To obtain an inverse, we need the colums of the original matrix to be orthogonal to each other." This isn't true, you just need the determinant to be nonzero. Matrices with nonzero determinant are a set of measure zero, so you will never actually get one from any numerical procedure.
On the other hand, it IS true that when the determinant is very small, the inverse is very sensitive to noise. This isn't fixed by using the pseudoinverse, though. You just need to do careful error propagation.
=> Fixed wrong statement about inverting noise matrix

content/ch-paper-implementations/vqls.ipynb
VQLS chapter was giving a warning
Fixes #117
float() --> np.real()
output of statevector (which was being cast to float) had imaginary part of 0, so I believe discarding the imaginary part is intentional and used np.real() to suppress the warnings.
=> Fixed complex to float warnings in vqls

content/ch-applications/qaoa.ipynb
Several small typos in the QAOA section of the textbook.
Corrections of these typos.
I was reading through this section of the textbook and noticed several typos.
As it was open source I thought to go through quickly and make the changes.
=> fixed typos in qaoa.ipynb

_sass/components/_components.textbook__page.scss
Fixes #207 
There is a 4px-padding on `<code>`-tags, which is perfectly fine, when used inline, like here:
But fails badly, when used in a multiline block. Because then, the first line (and only the first one) gets intended by 4px, like here:
I fixed it by applying "padding: 0px;" to `<code>`-tags that are direct childs of `<pre>`-tags, which seems to be always the case, when using multilines.
I checked all occurances (inline and multiline) and it looks good to me. 
Another approach i tried was to remove the padding completely, but it gets a too little tight on inline-tags then.
=> no padding, when code is used in a pre (non-inline code blocks)

_sass/components/_components.images.scss, _sass/main.scss
Fixes #226 
Now SVGs occupy 100% of the container, no more. A potential problemI've detected is that the reading area is too small.
=> Fix svg width

content/ch-algorithms/quantum-fourier-transform.ipynb
Typos in chapter 3.6 for QFT
1. "Let’s now encode ~~the~~ a number in the computational basis. We can see the number 5 in binary is 101"
2. Ch 3.6 Section 6 Steps 3,4,5 Effect of CROT1 gate to |x1> depending on |x3> = (exp(2πi/2^3)x3)|1>
=> updated 3.6

content/ch-applications/hhl_tutorial.ipynb
section C typo: QPE is discribed in chapter 3 not 4
4 replaced by 3
=> 4.1.1HLL section C typo: QPE is discribed in chapter 3 not 4

_includes/head.html, _includes/js/thebelab.html
Thebelab loads and place CSS at the bottom of the `<head>` tag and overrides some properties of Jupyter Book, breaking the layout.
This PR modifies the way in which Thebelab is loaded to wait for all its styles to be loaded, then relocate Jupyter Book CSS sheets so they get the correct precedence.
=> Fix precedence between Thebelab and theme CSS

content/ch-applications/hhl_tutorial.ipynb
2 typos:
4.1.1hhl 4B typo "and instance"
4.1.1hhl 4B typo "redaout"
1. "and instance" changed to  "an instance"
2. "redaout" to "readout"
=> 4.1.1hhl 4B typo an instance

_includes/sidebar.html
fixing dead link for c-sidebar__title.
this fixes #354
=> sidebar title aka fix #354

content/ch-states/single-qubit-gates.ipynb
The mathematical definition of Pauli-Ymatrix (in terms of outer product) was incorrect, i.e. the signs were flipped.
Changed the signs of the relevant terms.
With a pen and a piece of paper.
=> Corrected definition of Pauli-Y matrix

_includes/head.html, _includes/search/lunr/lunr-en.js, _includes/segment.html, assets/js/page/dom-update.js
Fixes #325
Factor out a helper function to asynchronously load scripts and use it to coordinate the initialization of some libraries such as lunr, the search engine.
Compared errors in the console before and after the modification.
=> Ensure the engine script is initialized after the engine is loaded

content/ch-algorithms/shor.ipynb
Updated markdown code for reference in Shor chapter, Fixes #456 
`[arXiv:quant-ph/0205095](arXiv:quant-ph/0205095)` was changed to:
`[arXiv:quant-ph/0205095](https://arxiv.org/abs/quant-ph/0205095)`
Link now works as expected taking you to Beauregard's paper repo in the arxiv.
=> fixed link to Beauregard reference

content/ch-applications/hhl_tutorial.ipynb
Fixes some of #309 but not all
Deprecated qiskit functions were replaced by newer once:
IBMQ.load_account()
IBMQ.get_provider().get_backend('ibmqx2')
shots were set to 10 and result added.
It is running (no errors anymore, which was the goal of the changes), but gives wrong results as the constant t and m are not defined (rest of the issue of #309).
=> changed all deprecated methods in 4B

content/ch-quantum-hardware/measurement-error-mitigation.ipynb
Significant typo in 5.2 Measurement Error Mitigation #464
Fixes #464
|00> to |01> in the line -
The information gathered from the basis states  ||00⟩ ,  ||01⟩ ,  ||10⟩  and  ||11⟩  can then be used to define a matrix, which rotates from an ideal set of counts to one affected by measurement noise. This is done by simply taking the counts dictionary for  ||00⟩ , normalizing it so that all elements sum to one, and then using it as the first column of the matrix. The next column is similarly defined by the counts dictionary obtained for  **||01⟩** , and so on.
=> Fixing a typo in measurement-error-mitigation

_data/toc.yml
This chapter is ready but is not currently showing on the site. This will add the chapter to the table of contents, which will publish the chapter.
=> add case-for-quantum to TOC

Makefile, scripts/create_redirections.py
Reordering chapters is something natural and we need a way to redirect readers from an outdated URL to the new one.
Added a script to define and create HTTP redirections.
Added this script to makefile.
The new script is conservative by default and will not overwrite an existing file unless you explicitly pass `--overwrite`. Pass it during development since the build directory is not clean up before generating. For production environemnts, it is better to avoid undesired file overwrites.
=> Add script to create HTML redirections.

_sass/page/components/_components.page.scss
Problematic line of css was forcing images to scale strangely, notably in shor's algorithm and the QIP chapters. I have removed the line.
=> Fix Strange Image Sizings

content/ch-algorithms/shor.ipynb
While using Matplotlib 3.3.0:
```
MatplotlibDeprecationWarning: The 's' parameter of annotate() has been renamed 'text' since Matplotlib 3.3; support for the old name will be dropped two minor releases later.
app.launch_new_instance()
```
This pull request will update the notebook to the most recent Matplotlib standards.
I renamed the "s" argument to "text"
Before update:
After update:
Pull request will break period finding as the "text" argument throws an exception
``` TypeError: annotate() missing 1 required positional argument: 's'```
I think it's best to let this request wait until matplotlib 3.3.0 is more standard.
=> Matplotlib 3.3.0 Update: arg s => text

content/ch-appendix/linear_algebra.ipynb
=> Fix: Typo in Pauli Matrices

content/ch-states/representing-qubit-states.ipynb
Equation typo made the result show "\x | psi" instead of just the letter "x" and the symbol "psi".
This typo comes from PR #575, which switched "x" and "psi" but left the "\\" in its old place.
=> Equation typo

content/ch-algorithms/teleportation.ipynb
Changed occurrences of "initialise" and "initialisation" to "initialize" and "initialization" respectively
While the spellings were not incorrect, there was inconsistent usage throughout the section of "s" vs "z". Other relevant documentation (https://qiskit.org/documentation/stubs/qiskit.extensions.Initialize.html) uses the "z" spelling so I changed them for consistency.
=> Section 3.2 > Change initialise to initialize for consistency w/ other docs

content/ch-gates/oracles.ipynb
Corrected grammar: changed 'how an oracles work' to 'how an oracle works'.
Replaced word: Replaced 'classical' with 'quantum'
Paragraph 3 discusses the reason to implement the classical algorithm in a reversible fashion due to the fact that all quantum operations are to be unitary. However, this does not simply mean replacing the boolean gates with their "quantum" counterparts. 
The quoted text had "classical" instead which is incorrect.
=> 2.6 Corrected grammar and replaced word

content/ch-quantum-hardware/cQED-JC-SW.ipynb
The definition for the Jaynes-Cummings Hamiltonian had a typo where instead of a "+", a "-" was present. Changed "+" to "-".
As pointed out in issue #699 , and verified through http://aliramadhan.me/files/jaynes-cummings-model.pdf
=> 6.4 Fixes issue #699

content/ch-gates/phase-kickback.ipynb
Replace "rightmost" with "leftmost"
The text says that the rightmost qubit is rotated, but in the picture
above, it is clear that the leftmost qubit is the one that is rotated.
=> 2.3 Fix typo (rightmost -> leftmost)

requirements-dev.txt
pin the `nbconvert` version to 5.6.1
`nbconvert` 6.0 currently [breaks the build](https://travis-ci.com/github/qiskit-community/qiskit-textbook/builds/183710951). this PR pins it to the previous version (i.e., 5.6.1) which resolves build failures until 6.0 can be properly reviewed and appropriate updates made to support it.
resolves #743
=> pin nbconvert version

_sass/components/_components.book__layout.scss
allow navigation sidebar to be closed when opening in mobile
fixes #689 
CSS has been updated to account for opening the sidebar on smaller screens. more specifically, an additional media query was added to account for screen widths smaller than the default sidebar width.
this change was made to allow users to more easily be able to navigate the textbook on a smaller screen (e.g., mobile device)
=> Support closing sidebar in mobile

content/ch-quantum-hardware/randomized-benchmarking.ipynb
Fix broken link to simultaneous RB notebook
Fixes #747 
Updated the link to the example of simultaneous RB (1Q RB and 2Q RB) notebook
The current link is broken and does not properly redirect readers to the simultaneous RB notebook
=> 5.3, 4 Update broken link

content/ch-gates/multiple-qubits-entangled-states.ipynb
#Changes made
Fixed the follwing link
https://qiskit.org/textbook/ch-states/atoms-computation.ipynb --> https://qiskit.org/textbook/ch-states/atoms-computation.html
The current link is broken. The change is necessary for the link to work.
=> 3.1 Fixed broken link to "The Atoms of Computation".

content/qiskit-textbook.bib
Replace commas in `.bib` file with `and` keyword
When using the natbib package, using a comma between authors makes all but the last names take their initials. [The correct way in natbib to separate authors is with the word "and".](https://tex.stackexchange.com/questions/36396/how-to-properly-write-multiple-authors-in-bibtex-file)
Forgive me if this file is not meant for natbib.
=> Fix author separator in .bib file

content/ch-algorithms/quantum-fourier-transform.ipynb
Fixes #756 
Updated the link to section 6 and changed the heading of section6
The link referred to a different section.
The heading was for 1-qubit while the content was for 3-qubits
=> 3.7 Fixed Issue756 by updating the QFT Notebook

content/ch-quantum-hardware/measurement-error-mitigation.ipynb
fixes #732 by updating the state of the qubits in the markdown cell and code
The content specified that the state (|00>+|11>)/sqrt(2) is taken but the code had (|01>+|10>)/sqrt(2)
=> 5.2 Fixes issue732 by updating the notebook

content/ch-algorithms/shor.ipynb
Update the Shor's Algorithm's notebook to use `pandas `instead of `tabulate`.
Fixes #733 
Updated the code to use `pandas` instead of `tabulate` to display data in a table
`tabulate` is not available/pre-installed in the IBM Quantum Experience. therefore the running the notebook fails with `ModuleNotFound` errors.
=> 3.9 Replace tabulate with pandas

content/ch-states/representing-qubit-states.ipynb
1.3 fixed typos in the paragraph right above 'contents'
added 'the', 'to', and a comma in the paragraph right above 'contents' 
for readability
=> fixed typo in chapter 1.3

content/ch-appendix/linear_algebra.ipynb
Changed: |v_s1> + .... + |v_sr> to b_1 |v_s1> + ... + b_r |v_sr>
The missing coefficients were a source of confusion and adding these coefficients makes the equation much clearer.
=> Ch: Appendix Linear algebra; Added missing coefficients to ket vector expansion

content/ch-quantum-hardware/measurement-error-mitigation.ipynb
**Before**: This time we find a more interesting matrix, and one that is not invertible.
**After**: This time we find a more interesting matrix, and one that we cannot use in the approach that we described earlier.
Also corrected some code semantics where qiskit is imported as `from qiskit import *`. But in some places, code such as 
```python
backend = qiskit.Aer.get_backend('qasm_simulator')
job = qiskit.execute(meas_calibs, backend=backend, shots=1000)
```
has been used instead of
```python
backend = Aer.get_backend('qasm_simulator')
job = execute(meas_calibs, backend=backend, shots=1000)
```
which is more popularly used.
I also changed `from qiskit import *` to
```python
from qiskit import QuantumRegister, QuantumCircuit, Aer, execute
```
for the sake of only importing modules that …
=> 5.2 Fixed #731 and corrected code semantics

content/ch-algorithms/grover.ipynb
Changed wording from adding a negative phase to the state `0` to adding a negative phase to every state **except** 0.
Unless my understanding is incorrect, after transforming the state `|s>` to `|0>`, we apply a negative phase to every state **except** `|0>`, and leave that untouched. 
An example of the operator can be described as follows:
| 1 | 0  | 0  | 0  | 0  |
|---|----|----|----|----|
| 0 | -1 | 0  | 0  | 0  |
| 0 | 0  | -1 | 0  | 0  |
| 0 | 0  | 0  | -1 | 0  |
| 0 | 0  | 0  | 0  | -1 |
In this operator, the state `0` is left untouched, and every state orthogonal to it has a negative phase.
=> 3.10 Fix incorrect wording about reflection around the state s.

content/ch-applications/satisfiability-grover.ipynb
Mentioned best classical algorithms so that the reader does not believe Grover beats best classical algorithm at 3-SAT. Elaborated on the relationship between Grover search and Boolean satisfiability.
see #778
=> [4.1.4] Mention best classical algorithms in Grover/SAT

content/ch-gates/phase-kickback.ipynb
Used HTML lists instead of markdown lists for the 'quick exercises' section at the bottom of the page
Markdown lists were not rendering properly due to the images between the list items
=> [2.3 Phase Kickback] Use HTML lists instead of markdown (fixes #788)

content/ch-applications/qaoa.ipynb
It's discrete variable, not discreet
https://en.wikipedia.org/wiki/Continuous_or_discrete_variable
https://www.grammarly.com/blog/discreet-discrete/#:~:text=Discreet%20and%20discrete%20are%20homophones,Discrete%20means%20distinct%20or%20unconnected.
=> 4.1.3 Fixed misspelling of 'discreet' -> discrete

content/ch-applications/hhl_tutorial.ipynb
Fixed branding: IBM Q Experience --> IBM Quantum Experience
Name was incorrect.
=> Fix IQX branding

content/ch-applications/satisfiability-grover.ipynb
Fixes #890 
Changed link in 4.1.4 "Solving Satisfiability Problems using Grover's Algorithm" so it redirects to the appropriate earlier section in the Qiskit Textbook.
Current link leads to a "Page Not Found." This change makes the link go to the appropriate page in the Qiskit Textbook.
=> 4.1.4 Fixed dead link

content/ch-labs/Lab01_QuantumCircuits.ipynb
Changed the spelling of 'tolerent'[sic] to 'tolerant' in Lab01 Part2
=> Lab01 Part2 Fixed misspelling of 'tolerant'

content/ch-labs/Lab01_QuantumCircuits.ipynb
In Lab01 Part2.1 changed spelling of '[...] is triganular [...]' to '[...] its triangular [...]'
=> Lab01 Part2.1 Fixed misspelling of 'triangular'

_includes/sidebar.html, _sass/components/_components.book__layout.scss, _sass/components/_components.page__onthispage.scss, assets/custom/custom.css, assets/images/chevron--down.svg
the language switcher position has been changed to fixed so it always visible as the sidebar scrolls
Resolves #978 
making the switcher position fixed and always visible ensure users are aware of the ability to change language
=> update position of language selector

content/ch-algorithms/deutsch-jozsa.ipynb
Under section 1.3, the probability of measuring `|0>^n` has its coefficient as `1/2^n` within the modulus squared when it really should be `1/\sqrt{2^n}`.
For a collection of n qubits, probability of measuring a particular eigenstate is the modulus square of `1/\sqrt{2^n} x <relevant_summation_terms>`.
=> 3.2 Fixed math typo

CONTRIBUTING.md, README.md, i18n/locales/ja/guideline-ja.md
Resolves [#979 ](https://github.com/qiskit-community/qiskit-textbook/issues/979)
- Added link to [“ CONTRIBUTING.md”](https://github.com/qiskit-community/qiskit-textbook/blob/master/CONTRIBUTING.md) on README.md.
- Added "Translation Guidelines" chapter and "Contributing Guidelines to the Japanese edition" on  CONTRIBUTING.md.  
- Added new file of "Contributing Guidelines to the Japanese edition" under i18n/locales/ja.
While we are drafting the guidelines for multi-language translation support, we need the guidelines for updating Japanese edition which has been already released.  This guidelines can help people to contribute the textbook.
=> Add link to contribution guidelines and update guidelines

_includes/topbar.html, assets/images/launch.svg
Link should use the "launch" icon instead of the rightarrow
To be consistent with design throughout qiskit.org
=> change icon for linking to github

content/ch-algorithms/quantum-fourier-transform.ipynb
I have fixed indexes of the two-qubit state in Section 5, in the statement that starts with "The action of $CROT_k$ on the two-qubit state $\vert x_j x_k\rangle$". The new version of the state is "$\vert x_l x_j\rangle$". 
See the issue 964 and comments. Here the summary:
1. In the sentence that starts with "The action of $CROT_k$ on the two-qubit state $\vert x_j x_k\rangle$", the order of the indexes, j and k, of the state $\vert x_j x_k\rangle$ is inconsistent respect to the subsequent 2 mathematical expressions, it is reversed.
2. Furthermore, the index of the state of the first qubit should be different from $k$, the index of $CROT_k$, to be consistent with the index of UROT in the QFT circuit figure in section 5 and the explanation in the steps 1-4.
=> 3.5 Fixed issue 964: Inconsistency with indexes in section 5

content/ch-demos/chsh.ipynb
- Fixed a cell tag
- Cell tag was not the keyword needed to remove the title on the website (and avoid duplicate titles)
- I think this needed to happen in a separate PR to avoid destroying author history
=> [CHSH] correct cell tag

content/ch-algorithms/quantum-key-distribution.ipynb
Made some changes in documentation/text for fixing grammatical mistakes and for consistency. For eg:
- its essential -> it is essential
- no-one -> no one (see the recommended usage at [Grammarly](https://www.grammarly.com/blog/no-one-noone/) )
- X-basis -> $X$-basis for consistent notation
- Other minor changes
- The changes are intended to correct grammatical mistakes and maintain consistency (for e.g. in existing version, X-basis is written in text as X-basis as well as $X$-basis. This has been changed to $X$ everywhere). There are no technical/code changes.
=> 3.12 fixed some grammatical mistakes in 3.12 Quantum Key Distribution

content/ch-states/images/half-adder.svg
Fixing the image used to depict the first step in building a half-adder using quantum circuits, as pointed out in #966 
Image in section changed from:
to:
Image didn't match the text below it, in "Chapter 1.2" section [4.3 Adding with Qiskit ](https://qiskit.org/textbook/ch-states/atoms-computation.html#4.3-Adding-with-Qiskit-) 
The text below it mentions "blank space" and "barriers" which aren't there in the current version of the image.
=> 1.2 (Section 4.3) Fix image depicting the first step in building a 'quantum' adder

content/ch-gates/proving-universality.ipynb
An expression in section 2.2 looks like:
$\left\langle \psi_0 |U^\dagger U| \psi_1 \right\rangle$
Whereas it should look like:
$\left\langle \psi_0 \right|U^\dagger U\left| \psi_1 \right\rangle$
Added \left and \right where they were missing.
The expression is much easier to read if $\left\langle \psi_0 \right|$ looks like one item, and $\left| \psi_1 \right\rangle$ looks like one item.
=> 2.2 Fixed inconsistent scaling in Dirac notation

content/ch-gates/phase-kickback.ipynb
Removed extra "if the" from quick exercise question.
Its a typo.
=> 2.3 Fix typo introduced in previous commit ccc3ff4

content/ch-quantum-hardware/Jaynes-Cummings-model.ipynb
1. Corrected the following spelling errors:
consting -> consisting
enegery -> energy
Hamintoninan -> Hamintonian
ue to -> due to
disscussed -> discussed
2. Added full stops at the end of several sentences. Some examples are:
"Next we define some helper functions that we will use for fitting and interpreting our data"
"Here we send our pulse sequence to the hardware"
"And then we access the measurement data for the high power resonator spectroscopy scan"
"Finally we plot the high power resonator spectroscopy next to the low power scan from the previous section and use the shift in resonator frequency to calculate χ"
"For this experiment our microwave drive doesn't have to be π-pulse"
3. Added a comma after chapter in the following sentence:
"In this chapter we introduce the Jaynes-Cummings …
=> 6.5 Exploring the Jaynes-Cummings Hamiltonian with Qiskit Pulse: Fixing the typos

content/ch-quantum-hardware/hamiltonian-tomography.ipynb
I have fixed the following spelling errors:
comutators -> commutators
notationaly -> notational
eignvalues -> eigenvalues
frequecies -> frequencies
I have also replaced 'etc' with 'etc.', which is the correct grammatical form of writing it.
I have fixed the spelling errors to improve readability.
=> 6.7 Hamiltonian Tomography: Fixing spelling errors

content/ch-quantum-hardware/accessing_higher_energy_states.ipynb
I have replaced 'ie' with 'i.e.,' and 'etc' with 'etc.'. 
A fullstop is missing in the following sentence, which I have added.
"(Note: If the plot looks off, rerun the notebook)"
The replaced forms of 'ie' and 'etc' follow the correct usage.
=> 6.2 Accessing Higher Energy States: Fixing the typos

requirements-dev.txt
`jinja2` has been updated to version 3.0.0 (as of May 11).
this change is resulting in build failures running nbconvert:
```
jinja2.exceptions.UndefinedError: 'nbformat.notebooknode.NotebookNode object' has no attribute 'tags'
```
`requirements-dev.txt` has been updated to freeze `jinja2` at version `2.11.2`
the build can complete and book successfully created
=> resolve build error

content/ch-applications/vqe-molecules.ipynb
Changed "emphasising" to "emphasizing."
"Emphasizing" is the more commonly accepted spelling.
=> 4.1.2 Fixed misspelling of "emphasizing"

content/ch-states/representing-qubit-states.ipynb
Changed "...we use `execute` to run our circuit..." to "...we use `run` to execute our circuit..."
The run() method of statevector simulation is used to execute circuit but the opposite was written in the explanation of the code
=> 1.3 Fixed explanation of running circuits using statevector simulation

content/ch-appendix/linear_algebra.ipynb
Original version:
Changed to:
The signs of lambda^2 and 1 seem to be swapped.
=> 8.1: math typo in equation finding eigenvalue

CONTRIBUTING.md
I have fixed a broken link. It was wrong previously I corrected it to right path.
> If you are unfamiliar with git, you can follow this guide to making contributions:
[Github Desktop Tutorial](https://github.com/firstcontributions/first-contributions/blob/master/github-desktop-tutorial.md)
The `Github Desktop Tutorial` was broken and it is replaced to a corrected [link](https://github.com/firstcontributions/first-contributions/blob/master/gui-tool-tutorials/github-desktop-tutorial.md)
If you click on the previous link (Quoted one) then you will see an error. But if you click on the link that is added by me then you will end up at right place.
=> Fixed a broken link in CONTRIBUTING.md

content/ch-algorithms/quantum-key-distribution.ipynb, content/ch-gates/oracles.ipynb
=> Fixing grammatical errors in 'uncomputation'

content/ch-applications/quantum-edge-detection.ipynb
Fixed some latex formatting / removed "NISQ"
- Some of the characters should be in text font (not italics) as they're not individual variables
- We prefer to avoid NISQ, just "noisy" or "today's" devices is fine
=> terminology / formatting in QHED Chapter

qiskit-textbook-src/qiskit_textbook/games/hello_quantum.py
Replace `BasicAer` with `Aer`
I don't think `BasicAer` supports `AerSimulator`.
=> [9.1] Update hello_quantum.py

content/ch-states/representing-qubit-states.ipynb
=> 1.3. ch-states Changed formula for normalization constraint

content/ch-states/representing-qubit-states.ipynb
Quick exercise suggests using plot_bloch_sphere_spherical() function. The correct function to use here is plot_bloch_vector_spherical().
=> 3.2 A section instructs using incorrect function

content/ch-states/representing-qubit-states.ipynb
here i have added line [3275-3278]
for visual representation of qubit it's give clear state of qubit and show how different gate acts on qubit state,
and also difines all gates in easy way!
=> Update reprensentating -qubit-state.ipynb(easy qubit state representation)

content/ch-algorithms/quantum-phase-estimation.ipynb
Fixes #1227
Updated the wavefunction notation in the 1.2 mathematical foundation section to use the same ket notation as previous sections.
The notation used in previous sections always wrote the wavefunction psi as a ket to distinguish it as a quantum state (as opposed to a normal variable).
=> [3.6] Standardize ket notation in QPE section

content/ch-states/atoms-computation.ipynb
Replaced 64 with 128 as 2^7 is 128. We are using 8 bits to represent 2^0 to 2^7.
=> [1.2] Fixed a calculation mistake and added clarity to describe CNOT gate

content/ch-algorithms/teleportation.ipynb
Fixes #1268
Closed the hyperlink tag on the section header.
This fixes the broken hyperlink so we can link to this section header.
=> [3.10] Broken hyperlink for "Understanding Quantum Teleportation" section header

README.md
Removed Abe's contact details from the textbook.
Abe no longer works at IBM and any emails to his account will not be received.
=> Remove Abe from contact details

content/ch-algorithms/quantum-phase-estimation.ipynb
In one place, the controlled U gate is called CU. In three others, it was called C-U. Here I’m changing them to all say CU.
I changed three occurrences of C-U (for a controlled U gate) to CU, to be consistent with the first time the CU is introduced.
My decision here is to change C-U to CU, because the hyphen was rendering in LaTeX math as a minus. That was a source of confusion for me as a first-time reader: it looked like some gate C, minus some gate U applied 2^j times. On the other hand, if a hyphen is preferable for some other reason I don’t know about, then `C\text{-}U` would be a good option.
=> Make the name for controlled U gates consistent

environment.yml
- pin Python to 3.7.* instead of 3.7.0 (`=3.7` is the same as `==3.7.*`, but `==3.7` is `==3.7.0`)
- depend on matplotlib-base instead of full matplotlib, which avoids pulling in large qt dependency, which goes unused in containers
This fixed installation e.g. on mybinder.org, where the strict pinning of old Python 3.7 caused an unresolvable env.
=> environment.yml: allow any Python 3.7

content/ch-gates/oracles.ipynb
"The effect of this is to ~~copies~~ **copy** the information over..."
The verb after “to” should be in the base form.
=> [2.6] Fixed Grammar Error "to copies"

content/ch-gates/multiple-qubits-entangled-states.ipynb
kronecker product is more precise than tensor product.
=> Changed tensor to kronecker

qiskit-textbook-src/setup.py
Remove newline in setup.py `description` string.
The newlines don't work with setuptools 59+ which
causes pip install to fail.
Closes #1327
=> Avoid newlines in setup.py description

content/ch-states/atoms-computation.ipynb
[1.2] Added space between 'QuantumCircuit.' and 'The'
Minor grammar mistake
=> [1.2] Added space between 'QuantumCircuit.' and 'The'

content/ch-algorithms/superdense-coding.ipynb
Fixed the encode_message function character validation for superdense coding
Previously the function claimed to validate characters in the comments but actually did nothing meaningful.
=> [3.12] fix encode_message character validation

README.md
Added pipenv install instructions to README.md
The quotes around the URL seem to be necessary in order to recognize the egg fragment
I guess you can argue about `pipenv` but a lot of people use it for virtual environments. Getting the textbook installed on pipenv wasn't entirely trivial and took me like 2 minutes of trial and error.
=> [README.md] Add pipenv install instructions to

content/ch-applications/qaoa.ipynb
shouldn't the 2-qubit operations come first?
=> [4.1.3] switch cost and mixing unitary

content/ch-applications/hhl_tutorial.ipynb, requirements-dev.txt
- Pinned markupsafe to `2.0.1`
- Fixed syntax errors in HHL notebook
- Markupsafe introduced breaking changes which broke build process (see https://github.com/pallets/markupsafe/issues/284#issuecomment-1044168203).
- Backslashes were not escaped in HHL notebook
=> Fix build errors

content/ch-quantum-hardware/density-matrix.ipynb
The sentence describing the off-diagonal elements of the density matrix has a few typos in it. 
Typos should be fixed as they can lead to confusion in peoples learning process.
=> [5.5] Corrects grammar describing the elements of the density matrix.

i18n/locales/ja/ch-states/single-qubit-gates.ipynb
- Modify confusing texts
- Some Japanese seemed confusing, so I fixed them: the gates HZH act on the Z-basis rather than the Z-basis acting on the gates.
=> [1.4] Fix Japanese in single-qubit-gates.ipynb

content/ch-algorithms/simon.ipynb, i18n/locales/ja/ch-algorithms/simon.ipynb
Changed the number of qubits required when running Simon's algorithm on a real machine.
When b = "11", Simon's algorithm requires n*2 qubits.
=> [3.4] Fix minimum number of qubits required for IBMQ.

content/ch-applications/vqe-molecules.ipynb
fixed spelling of parameters
typo
=> 4.1.2 Fixed misspelling of 'parameters'

content/ch-algorithms/grover.ipynb
Fixed [ch-algorithms/Grover's Algorithm] 3.1.2 and 2.1.2 #1374
fixed by typecasting `x.configuration().n_qubits` inside the lambda function as:
```
device = least_busy(provider.backends(filters=lambda x: int(x.configuration().n_qubits) >= 3 and 
not x.configuration().simulator and x.status().operational==True))
print("Running on current least busy device: ", device)
```
Throws `TypeError: '>=' not supported between instances of 'str' and 'int'` on running the code example
=> Fixed #1374

content/qiskit-textbook.bib
- Fix URL in BibTeX file
- Use SSL(`https`) URL
- Now `https://community.qiskit.org/textbook` has been moved so I fix it
```console
$ curl -I https://community.qiskit.org/textbook
HTTP/2 301
date: Fri, 29 Jul 2022 04:51:55 GMT
location: https://qiskit.org/textbook
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 73233dffac1914d4-NRT
```
```console
$ curl -I https://qiskit.org/textbook
HTTP/2 301
date: Fri, 29 Jul 2022 04:53:22 GMT
location: https://qiskit.org/textbook/
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 7323401c8ad7afe1-NRT
```
- This repository has another BibTeX file 👀 
- …
=> Fix BibTeX file URL

content/ch-applications/qaoa.ipynb
Reverse bit-strings before evaluating cut sizes
Bit-strings in the counts dictionary are in little-endian format. However, input expected by the cut size evaluation function is not.
fixes #1495 
@bernalde
=> [4.1.3] reverse bitstrings

content/ch-labs/Lab02_QuantumMeasurement.ipynb
[Lab 2. Quantum Measurement] Lab uses Ignis (unmaintained since July 2022) [#1476](https://github.com/qiskit-community/qiskit-textbook/issues/1476)
Changed `from qiskit.ignis.mitigation.measurement import *` to `from qiskit.utils.mitigation import *`
The code example in [Lab 2](https://qiskit.org/textbook/ch-labs/Lab02_QuantumMeasurement.html) uses `qiskit.ignis`, which is unmaintained since July 2022 after being deprecated in Dec 2021.
=> [Lab 2. Quantum Measurement] Fixed the #1476

content/ch-quantum-hardware/density-matrix.ipynb
This PR is for solving issue #1453 
Changed the link to trace on Wikipedia in section [Trace and Positivity Conditions](https://qiskit.org/textbook/ch-quantum-hardware/density-matrix.html#Trace-and-Positivity-Conditions-) to eliminate extra ')'. 
There is an extra ')' after the link to Wikipedia which needs to be eliminated. It was due to '(' and ')' in the link to Wikipedia. I encoded them with '%28' for '(' and '%29' for '('.
=> [5.5] Fix the extra ')'

content/what-is-quantum.ipynb
Changed the value of the `value` attribute of `repeat_slider` function in the "Experiment 1" from `0` to `1`.
Fixed the issue #1512 
>>While tossing the coin with the simulator, the initial no: of coin/s is set to 0, which is obscured, and the simulator goes on to toss '0' coin/s and still gives a result, which in reality should not be the case.  
Changed it to be 1.
=> [What is Quantum?] off-by-one in coin toss simulator

.github/workflows/deploy.workflow.yml
The build / deploy is failing as the ruby setup action is deprecated. The deprecation notice recommends migrating to `ruby/setup-ruby@v1`, which is what I've done here.
=> Migrate ruby action

content/ch-states/single-qubit-gates.ipynb
Changed article in "The T-gate is a very commonly used gate, it is an P-gate with $\\phi = \\pi/4$" to 
"The T-gate is a very commonly used gate, it is a P-gate with $\\phi = \\pi/4$"
"an P-gate" should be "a P-gate" to agree with English article rules. Since the starting letter, 'p-', in p-gate (phase gate) is a consonant that is not silent, 'a' would be the correct article.
=> [1.4] Article change for grammatical correctness: changed 'an' to 'a'. 

content/ch-algorithms/quantum-counting.ipynb
Remove a duplicate `can` in the sentence.
Fix a duplicating `can` word in the sentence
Correct sentence
=> Fix a typo #3

content/ch-algorithms/quantum-counting.ipynb
Fix the `qft` function to work for n != 4 
If someone wants to vary the number of counting qubits, the function fails. Note that simply varying `t` a few cells below still does not work due to the hardcoded 4 in this cell:
```
qft_dagger = qft(4).to_gate().inverse()
qft_dagger.label = "QFT†"
```
although generalising to use the `t` variable instead would require some re-ordering.
=> [3.9] Fix qft function

content/ch-algorithms/deutsch-jozsa.ipynb
fixes #1562 
The problem which is reported is due to depreciation due to removal of `extend` method.
Found this in release notes     
The [`QuantumCircuit`](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.html#qiskit.circuit.QuantumCircuit) methods `combine` and `extend` have been removed following their deprecation in Qiskit Terra 0.17.0. This was done because these functions were simply less powerful versions of [`QuantumCircuit.compose()`](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.compose.html#qiskit.circuit.QuantumCircuit.compose), which should be used instead.
The removal of `extend` also means that the `+` and `+=` operators are no longer defined for [`QuantumCircuit`](https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit …
=> Fixes_composing_problem_issue 

_data/ja/messages.yml, _data/messages.yml, _includes/banner.html
Updates the banner to warn about deprecation of the legacy textbook website.
**Message:**
> On April 11, this site will be replaced with the new[ Qiskit Textbook](https://qiskit.org/textbook-beta). You will still be able to access these pages through the new platform.
=> Update banner message
