qiskit-community/qiskit-textbook

ch-algorithms/bernstein-vazirani.ipynb
ch-algorithms/deutsch-josza.ipynb
ch-algorithms/grover.ipynb
ch-algorithms/quantum-fourier-transform.ipynb
ch-algorithms/quantum-phase-estimation.ipynb
ch-algorithms/simon.ipynb
ch-algorithms/teleportation.ipynb
ch-applications/satisfiability-grover.ipynb
ch-applications/vqe-molecules.ipynb

Replaced the old version of accessing IBMQ provider

Update the Format of IBM Credential V2

---

qiskit-textbook.bib

Updated contributors .bib file 😄

Updated Contributors

---

ch-algorithms/deutsch-josza.ipynb

as per suggestions in PR #49. Hopefully these will clear things up.

Correct deutsch-josza.ipynb

---

ch-algorithms/deutsch-josza.ipynb

Corrected text to access concerns summarised in Issue #54 .

Fix Deutsch-Josza section

---

ch-prerequisites/qiskit.ipynb

The custom gate is a cx between 0 and 2, using 1 to intermediate. The original described it as a cx between 0 and 1, using 1 to intermediate.

Fixed description of the custom gate example

---

ch-prerequisites/linear_algebra.ipynb

Hilber
changed to
Hilbert
Contextually unitary matrices demonstrate the property of reversibility within Hilbert space, which is a generalization of Euclidean space. Thus, Hilbert spaces are n-dimensional extrapolations of the Euclidean space.

Erratum linear_algebra.ipynb Line 195

---

content/ch-gates/standard-gate-set.ipynb
content/ch-states/atoms-computation.ipynb

Typos found in atoms-computation and standard-gate-set

Fixes a few typos

---

content/ch-prerequisites/qiskit.ipynb
content/ch-states/introduction.ipynb

Update broken URLs for Introduction to Python and Jupyter notebooks and Introduction to Linear Algebra for Quantum Computing

Fix issue # 93

---

content/ch-prerequisites/linear_algebra.ipynb

fixed a typo in linear_algebra.ipynb

---

content/ch-algorithms/deutsch-josza.ipynb
content/ch-algorithms/quantum-fourier-transform.ipynb
content/ch-algorithms/quantum-phase-estimation.ipynb
content/ch-algorithms/simon.ipynb
content/ch-algorithms/teleportation.ipynb
content/ch-applications/satisfiability-grover.ipynb
content/ch-applications/vqe-molecules.ipynb

Fixes #108 
Fixes #109 
Fixes #112 
Fixes #113 
Fixes #114 
+ Adding it in VQE Chapter too (no issue for that)

Add missing provider variable

---

content/ch-prerequisites/linear_algebra.ipynb

Missing brackets in an expression

Fix a style typo

---

_config.yml

Use correct https://qiskit.org/textbook as Logo-Link

---

content/ch-states/atoms-computation.ipynb

Fixing some typos and grammar in Chapter 1.2 The Atoms of Computation

Ch 1.2 > typos and grammar fixes

---

content/ch-prerequisites/linear_algebra.ipynb

minor typo corrected  entires to entries

typo: minor typo changed

---

content/ch-states/atoms-computation.ipynb

Fixed Spelling Error in Atoms of Computation

---

content/ch-quantum-hardware/measuring-quantum-volume.ipynb

Kick travis and rebuild qv

---

content/ch-algorithms/bernstein-vazirani.ipynb
content/ch-algorithms/quantum-phase-estimation.ipynb
content/ch-algorithms/teleportation.ipynb
content/ch-applications/satisfiability-grover.ipynb
content/ch-prerequisites/qiskit.ipynb
content/ch-quantum-hardware/measurement-error-mitigation.ipynb
content/ch-states/atoms-computation.ipynb

Replaced all instances of `qiskit.tools.visualization` with `qiskit.visualization`

Change qiskit.tools.visualization -> qiskit.visualization

---

content/ch-applications/qaoa.ipynb
content/ch-applications/satisfiability-grover.ipynb

- Fixing a link, that was based on legacy url structure
- Added a missing space after a reference link
- As the needed gates are no longer "in the order of thousands" i've rewritten that, to be more general

(Minor PR) Fixing a dead Link, outdated wording and a missing space

---

content/preface.md

Made coherent with qiskit-textbook.bib (added myself as contributer)

Updated list of contributors

---

LICENSE.txt
README.md
content/preface.md

Updated license, codeblocks

---

content/ch-quantum-hardware/accessing_higher_energy_states.ipynb

spell-check "seperatrix" -> "separatrix" in higher energy states section

Build textbook

---

content/ch-upcoming/0.ipynb
content/preface.md

The first Japanese translation.

first Japanese translation

---

_config.yml
requirements.txt

added torch and torchvision reqs

---

content/ch-ex/hello-qiskit.ipynb
content/ch-ex/hello_quantum.py

An exercise notebook was added ('hello-qiskit.ipynb') as well as an associated helper file ('hello_quantum.py').
Given to my course at the University of Basel (for two years).
* Covers the material of 1.2 and 1.3.
* Note that the other exercises are labelled as 'ex1', 'ex2', etc. I did not use this convention. I would suggest that it is the other titles that should be changed to something more verbose.
* This exercise is interactive, using Jupyter widgets. We need to see if it works on the website.

add interactive exercise

---

_includes/buttons/binder.html
_includes/js/thebelab.html
_includes/segment.html

I've added a `trackCta()` function to the global object `window`. It takes an action parameter, which is a string describing the call to action. @frankharkins feel free to suggest me other descriptions.
With these changes, we can keep track about enabling interactivity, going to IQX and running some specific cell.

Add CTA analytics

---

_includes/js/thebelab.html
_sass/components/_components.iqx.scss
_sass/main.scss

Includes re-styling of "the use hardware notice".
Add analytics to the "run using IQX" links.

Refactor the code for creating use-hardware cells.

---

content/ch-ex/hello-qiskit.ipynb
content/ch-ex/hello_quantum.py

Please notice I did not add it to the TOC.

Modified hello_quantum.py to make it compatible with the textbook

---

_config.yml

point to correct github repo

---

content/ch-ex/hello-qiskit.ipynb
qiskit-textbook-src/qiskit_textbook/games/hello_quantum.py

* The text for all puzzles was improved
* An issue with the line-based visualization was found and fixed
* A section on how people can make their own puzzles was added

Improve and fix Hello Quantum

---

content/ch-ex/hello-qiskit.ipynb

Two cells had typos. Now they don't.

Correct circuit display for sandboxes

---

_data/toc.yml

Fixed missing links

---

content/ch-states/representing-qubit-states.ipynb

Fixed redirect issue of mathematics prerequisite.

---

_config.yml
content/ch-machine-learning/machine-learning-qiskit-pytorch.ipynb
requirements.txt

Revert "removed pytorch requirement"

---

_sass/components/_components.book__layout.scss
_sass/components/_components.qiskit__navbar.scss
assets/custom/custom.css

fixed problems with navbars and scrolling

---

assets/custom/custom.css
content/ch-algorithms/quantum-key-distribution.ipynb

fixed tables

---

content/ch-algorithms/teleportation.ipynb

Fix for #356

---

_data/toc.yml
assets/custom/custom.css
content/ch-algorithms/quantum-key-distribution.ipynb

build site

---

content/ch-gates/introduction.ipynb

This should hopefully resolve #404

Updated Chapter 2.1 to maintain consistency

---

content/ch-gates/proving-universality.ipynb

A brief discussion of the motivation for QCs was included here, but it should be done elsewhere (such as PR #431).

Remove content from 'proving universality'

---

content/ch-states/representing-qubit-states.ipynb

Simple typo
Fixes #475 
peices --> pieces in section 1.3 para 2

changed minor typo in C1.2

---

_includes/qiskit_navbar.html

Navbar link was broken, now points to relevant page.

Fix broken navbar link

---

content/ch-gates/proving-universality.ipynb

Spelling correction

---

_includes/qiskit_navbar.html
_includes/topbar.html
_sass/components/_components.qiskit__navbar.scss

Also remove option to open 'what is quantum' in IQX (this page is only intended to be read as HTML).

Match navbar to qiskit.org

---

scripts/run_notebooks.py

use `os` and `sys` to generalise and clean up code.

clean up code in run_notebooks.py

---

CONTRIBUTING.md
content/ch-algorithms/bernstein-vazirani.ipynb
content/ch-algorithms/deutsch-jozsa.ipynb
content/ch-algorithms/quantum-fourier-transform.ipynb
content/ch-algorithms/shor.ipynb
content/ch-algorithms/simon.ipynb
content/ch-algorithms/superdense-coding.ipynb
content/ch-algorithms/teleportation.ipynb
content/ch-applications/hhl_tutorial.ipynb
content/ch-applications/satisfiability-grover.ipynb
content/ch-applications/vqe-molecules.ipynb
content/ch-gates/more-circuit-identities.ipynb
content/ch-gates/multiple-qubits-entangled-states.ipynb
content/ch-gates/phase-kickback.ipynb
content/ch-gates/proving-universality.ipynb
content/ch-machine-learning/machine-learning-qiskit-pytorch.ipynb
content/ch-paper-implementations/vqls.ipynb
content/ch-quantum-hardware/error-correction-repetition-code.ipynb
content/ch-states/case-for-quantum.ipynb
content/ch-states/representing-qubit-states.ipynb
content/ch-states/single-qubit-gates.ipynb

Second portion of spelling and grammer mistakes

---

content/ch-algorithms/grover.ipynb

Corrected spelling of 'intuition'.

3.10 Fixed misspelling of 'intuition'

---

qiskit-textbook-src/qiskit_textbook/tools/array_to_latex.py

Change `outstring` to `imagstring`.
`outstring` was never defined.

Fix typo in variable name

---

content/ch-applications/satisfiability-grover.ipynb
content/ch-machine-learning/machine-learning-qiskit-pytorch.ipynb

Translated two chapters in Japanese.
- 4.1.4 "Solving Satisfiability Problems using Grover's Algorithm" 
- 4.1.5 "Hybrid quantum-classical Neural Networks with PyTorch and Qiskit"

4.1.4, 4.1.5 Translated in Japanese

---

qiskit-textbook-src/qiskit_textbook/games/jupyter_widget_engine.py

A game-based tool has been added to the 'games' module.
It could be used in future game chapters, and will be used in workshops within the quantum experience.

[no chapter] add jupyter game engine for use in workshops

---

content/ch-gates/proving-universality.ipynb

replaced "an" with "a"
added hyphens to "single and two qubits"
improve readability

2.5 Fix a minor typo

---

content/ch-gates/more-circuit-identities.ipynb

Before: We know that the Hadamard transforms the states |0⟩ and |1⟩ to the states |+⟩ and |−⟩. 
After: We know that the Hadamard transforms the states |0⟩ and |1⟩ to the states |+⟩ and |−⟩ respectively.
Made correction to improve grammar.

2.4 Improved grammar

---

content/ch-algorithms/shor.ipynb

Escaped backslash character so the website can build correctly
was not properly escaped and was breaking the build

Escape backslash character

---

content/ch-algorithms/grover.ipynb

After some feedback from readers, I have:
- Linked back to earlier chapters to remind users of concepts they have already covered
- Emphasised this specific example problem is trivial and clarified the purpose of the example

[3.10 Grover] Incorporate feedback in to sudoku section

---

content/ch-applications/qaoa.ipynb

Fixed grammar of sentence "function. That maps..." -> "function, that maps"

4.1.3 Fixed grammar of sentence "function. That maps..." -> "function, that maps"

---

_data/toc.yml

add new hardware chapters to TOC

---

content/ch-prerequisites/setting-the-environment.ipynb

0.1 Fixed user config filename

---

content/ch-algorithms/shor.ipynb

Mentioned only 1 argument to gcd
Clarified one sentence: added the other argument to gcd (which is N) and added "proper" factor (if gcd = 1, that's technically also a factor of N, but not a proper factor)
The sentence was incomplete and incorrect.

3.9 Fixed broken sentence

---

content/ch-algorithms/quantum-key-distribution.ipynb

Added a missing row to one of the tables
It was missing: the line above the table suggests a change, but the table was the same as the one at the previous step in the text.

Add missing row in table

---

content/ch-applications/vqe-molecules.ipynb

Removed an import line that is a duplicate from a few lines above it
Less code is better

4.1.2 Remove duplicate import from code cell

---

_includes/qiskit_navbar.html

Added overview link to top bar
Need to match the rest of qiskit.org

add 'overview' to topbar

---

content/ch-quantum-hardware/error-correction-repetition-code.ipynb

5.1 fix content bug #770

---

content/ch-states/representing-qubit-states.ipynb

Fixed misspelling of "discussed"
See dictionary.

3.2 Fixed misspelling of "discussed"

---

content/ch-algorithms/deutsch-jozsa.ipynb

[3.2] Resolve #936

---

content/ch-quantum-hardware/measurement-error-mitigation.ipynb

Fixes #969; see issue for justification

[5.2] remove use of qc.qregs

---

_includes/head.html
_includes/hotjar.html

Added hotjar script to textbook pages
Allow users to provide feedback

enable hotjar script

---

_data/messages.yml
_includes/topbar.html

Link to beta testing form in sidebar
Want to make this as visible as possible without being intrusive

add link to beta testing form in right sidebar

---

content/ch-applications/hhl_tutorial.ipynb

[4.1.1] Fix 865

---

content/ch-gates/more-circuit-identities.ipynb

I have rephrased some sentences and have fixed some spelling errors to improve readability.

2.4: Rephrasing sentences and fixing spelling errors

---

content/ch-ex/hello-qiskit.ipynb

Fixed several spelling/grammatical errors.

9: Hello Qiskit Game

---

README.md

Better code block formatting in `README` and changed "Pip" to "pip" (as seen [here](https://pip.pypa.io/en/stable/)).
The code was improperly formatted which led to some minor difficulty in reading the instructions for installation. This PR addresses this issue.

Better code formatting for `README`

---

content/ch-algorithms/defining-quantum-circuits.ipynb

3.1 Fixed misspelling of "parameterized"

---

content/ch-labs/Lab01_QuantumCircuits.ipynb
content/ch-labs/Lab03_AccuracyQPE.ipynb
content/ch-labs/Lab08_QEC1.ipynb

execute --> backend.run  for Lab1 and make changes in Lab 8 so that the couple texts can get rendered correctly online.

corrections for Lab1 and Lab8

---

i18n/locales/ja/ch-states/atoms-computation.ipynb
i18n/locales/ja/ch-states/images/half-adder.svg

Added missing image to the japanese translation. Fix for #1126.

Ch 1.2 added half-adder image to Japanese translation

---

.github/workflows/deploy.workflow.yml
CONTRIBUTING.md
README.md
_includes/topbar.html
content/preface.ipynb
i18n/locales/ja/guideline-ja.md
i18n/locales/ja/preface.ipynb

this PR updates references to the default branch
the default branch has been renamed

update references to default branch

---

content/ch-quantum-hardware/density-matrix.ipynb

Corrected spelling from  inputing to inputting.

Fix minor typo

---

content/ch-applications/hhl_tutorial.ipynb
content/ch-applications/qaoa.ipynb
content/ch-paper-implementations/vqls.ipynb

Fixing misspelling of 'constant'

---

content/ch-quantum-hardware/density-matrix.ipynb

Fixed misspelling of 'parameterizing'

---

content/ch-quantum-hardware/density-matrix.ipynb

Fixed misspelling of 'arbitrary' and 'consisting'

---

content/ch-quantum-hardware/density-matrix.ipynb

Fixing misspelling of 'occurrence' on different line

---

content/ch-quantum-hardware/density-matrix.ipynb

Fixing misspelling of 'orthonormal'

---

content/ch-quantum-hardware/density-matrix.ipynb

Fixing misspelling of 'occurrence'

---

content/ch-applications/qaoa.ipynb

Minor corrections to grammar and spelling in the QAOA notebook.

4.1.3 Fix typos, grammar in qaoa.py

---

content/ch-gates/proving-universality.ipynb

Update proving-universality.ipynb(version table)

---

content/ch-algorithms/shor.ipynb

3rd chapter, 3.7.
Is it correct that we actually have 8 qubits?

[3.7] Typo?

---

content/ch-states/case-for-quantum.ipynb

Update case-for-quantum.ipynb(version table)

---

content/ch-algorithms/shor.ipynb

I noticed a period outside a displayed formula where the formula is at the end of the sentence, so I moved it inside.
The change is just a fix of punctuation.

Put period inside displayed formula

---

_data/toc.yml

Remove facial expression recognition chapter

---

content/ch-algorithms/quantum-walk-search-algorithm.ipynb

Cosmetic change and typo fix on the file `quantum-walk-search-algorithm.ipynb`.

cosmetic change and typo

---

content/ch-labs/Lab01_QuantumCircuits.ipynb

Fixed various typos
Typos cause great distraction to me, sometimes leading to interruption in reading and instead forking a repo, fixing said typos, and triggering a PR

[7.1] Fix various typos

---

i18n/locales/ja/ch-algorithms/quantum-phase-estimation.ipynb

The Japanese translation of the control was missing, so I added it.
If the problem statement is different, it will not be a problem, so it needs to be corrected.

[3.6] The Japanese translation of the exercise was incorrect.

---

content/ch-gates/proving-universality.ipynb

- Fix a typo in a formula
- Compared to [content/ch-gates/oracles.ipynb#L90](https://github.com/qiskit-community/qiskit-textbook/blame/8e635307742a6a34842fc11e170de47f5a980f1b/content/ch-gates/oracles.ipynb#L90) this seems to be a typo

[2.5] Fix a typo

---

content/ch-algorithms/deutsch-jozsa.ipynb

Fixed misspelling of the word 'oracle'

[3.2, 2] Fixed misspelling of 'oracle'

---

content/ch-demos/first-quantum-game.ipynb
qiskit-textbook-src/qiskit_textbook/games/qiskit_game_engine.py

An option was added to the `QiskitGameEngine` to allow the screen to be interactive. This was then documented in the relevant page (which isn't actually listed within the textbook).
Changes required for content in the QEC Summer School.

[Your First Quantum Game] Add optional feature to game engine

---

_data/ja/toc.yml

Updated toc.yml file for new Japanese translation of "4.2.2 Quantum Image Processing - FRQI and NEQR Image Representations  "

update ja toc.yml

---

qiskit-textbook-src/qiskit_textbook/games/hello_quantum.py

[games/hello_quantum] Fixed misspelling of 'corresponding'

---

content/ch-paper-implementations/tsp.ipynb

[4.2.4] Fix typo in 'because'

---

content/ch-states/atoms-computation.ipynb

Changed the description of what logic gates are.
The statement "basic operations of computing are known as logic gates" is not an accurate description of logic gates since logic gates are circuits that perform basic operations rather than being the operation itself.

[1.2] Update atoms-computation.ipynb

---

content/ch-applications/qaoa.ipynb

[4.1.3] Fixed typo in Appendix 2.1

---

content/ch-quantum-hardware/accessing_higher_energy_states.ipynb

This PR merges #1442; there was another occurrence of 'armonk' that needed changing.

Merge Omarshehab/patch-1

---

content/ch-quantum-hardware/accessing_higher_energy_states.ipynb

"ibmq_armonk" -> "ibmq_manila"

---

content/ch-quantum-hardware/calibrating-qubits-pulse.ipynb

Changed some typos from vaule to "value" and granurality to "granularity".

Fixed typos

---

_data/ja/toc.yml

Updated `_data/ja/toc.yml` related to the recent translation status.

Update Japanese toc.yml

---

i18n/locales/ja/preface.ipynb

Added new Japanese translator's name in Japanese preface.ipynb.

Update Japanese preface.ipynb

---

README.md

I have removed the github repo link of textbook beta and updated it with the latest released one.

Updated beta Github Link to Latest Released one
